source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Qiushi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Qiushi
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'KakaJSON'

end
